[package]
name = "messd"
version = "0.1.0"
authors = ["Stephen Molyneaux <shmolyne@uwaterloo.ca>"]

[dependencies]
block_accessor = { path = "lib/block_accessor" }
crc16 = "0.3.4"
heapless = "0.3.5"
bitflags = "1.0.3"
linux-embedded-hal = "*"
embedded-hal = "*"
streaming-iterator = "*"
nb = "*"
